version: "3.8"

services:
  app_cluster_1:
    build:
      context: .
    environment:
      - PORT=3000
      - INSTANCE_ID=cluster_1
    networks:
      - app_network

  app_cluster_2:
    build:
      context: .
    environment:
      - PORT=3000
      - INSTANCE_ID=cluster_2
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network

networks:
  app_network:
